# Pre-commit configuration
# See https://pre-commit.com for more information
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Python code formatting & linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --install-types, --non-interactive]

  # Security linting
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: [-r, src]
        exclude: tests/

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown]
        exclude: CHANGELOG.md

  # Security scanning with Trivy (using mxab/pre-commit-trivy)
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.15.0
    hooks:
      - id: trivyconfig-docker
        name: Trivy scan for configuration files
        args:
          - "--exit-code"
          - "1"
          - "--severity"
          - "HIGH,CRITICAL"
          - "--skip-dirs"
          - "./tests"
          - "."

  # Python dependency scanning
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        additional_dependencies: ["requests==2.32.4"]

  # Commit message formatting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Python syntax upgrade
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

# Configuration for specific hooks
default_language_version:
  python: python3.9

# Global excludes
exclude: |
  (?x)^(
    migrations/|
    __pycache__/|
    \.git/|
    \.tox/|
    \.venv/|
    venv/|
    \.pytest_cache/|
    \.mypy_cache/|
    build/|
    dist/|
    \.egg-info/
  )

# Fail fast - stop on first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: 3.0.0
